
project_id = "vqdlsidkucrownbfuouq"

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.process-rent-payments]
verify_jwt = false

[functions.send-email]
verify_jwt = false
