
project_id = "vqdlsidkucrownbfuouq"

[env]
SADAD_MERCHANT_ID = "8432581"
SADAD_SECRET_KEY = "STqZIjv58VQ+eYB/"
SADAD_WEBSITE = "https://alaraf.online"
PUBLIC_URL = "https://alaraf.online/customer-portal"
